### ISSUE TITLE
Unable to do something with the mysql_jwt.so produced file under Mac OS X Big Sur 11.5.2 + MySql 5.7.34

### ISSUE THREAD

**Issue by darelative** [addsict/mysql_jwt#1]
Hello yfuruyama ! Thank you so much for your reactivness, I dig out your 7 years old code that I sincerely found that is a pure dope! Congratulations for it.

So today's date, september 9th 2021:
- under Mac OS X Big Sur 11.5.2
- with MAMP 6.5 (latest) https://www.mamp.info/en/downloads/
- and MySQL 5.7.34

I ran:

``git clone https://github.com/yfuruyama/mysql_jwt.git && cd mysql_jwt``
``nano .gitmodules ``
``# replaced all "git@github.com:" by "https://github.com/"``
``git submodule init && git submodule update``
``nano picosjon/picosjon.h``
``# replaced the entire line 200 by : "isnan(n) || isinf(n)" because of the following error:``
``# "./picojson/picojson.h:200:3: error: no member named 'isnan' in namespace 'std'; did you mean simply 'isnan'?"``
``g++ -o mysql_jwt.so mysql_jwt.cc `mysql_config --cflags` -bundle``
``cp mysql_jwt.so `mysql_config --plugindir`/``

I succesfully get a mysql_jwt.so file.

Then, under a mysql terminal:
``mysql> show variables like '%compile%';``
``+-------------------------+----------+``
``| Variable_name           | Value    |``
``+-------------------------+----------+``
``| version_compile_machine | x86_64   |``
``| version_compile_os      | osx10.12 |``
``+-------------------------+----------+``

``mysql> select @@plugin_dir;``
``+----------------------------------------+``
``| @@plugin_dir                           |``
``+----------------------------------------+``
``| /Applications/MAMP/Library/lib/plugin/ |``
``+----------------------------------------+``

But from the moment I try to create the function as the domentation mentions, I get this:
``mysql> CREATE FUNCTION decode_jwt RETURNS STRING SONAME 'mysql_jwt.so';``
``ERROR 1126 (HY000): Can't open shared library 'mysql_jwt.so' (errno: 1 dlopen(/Applications/MAMP/Library/lib/plugin/mysql_jwt.so, 2): no suitable image found.  Did find: /Applications/MAMP/Library/l)``

I was thinking about the fact that maybe it should not be a .so file but a .dylib file, and after researches on internet I found a command idea like this one:
``g++ -I/Applications/MAMP/Library/include -c mysql_jwt.cc``
``g++ -bundle -undefined dynamic_lookup -o mysql_jwt.dylib mysql_jwt.o``
``cp mysql_jwt.dylib `mysql_config --plugindir`/``

but even with the mysql_jwt.dylib file, it also fail to create my function...

Your idea is really and exactly what I want, and to give you more context I need a similar function to be executed inside a MySQL PROCEDURE, taking as input a Jwt token, and then your function comes into the game by decoding it.

Thanks for your support, but if nothing can be done I'm currently looking at https://github.com/mysqludf/lib_mysqludf_sys for achieving a similar goal.

Best

**Comment by darelative** [comment]
After checks and checks, the problem was MAMP. Under Big Sur it comes with an already configured MySQL 5.7 which do not accept UDF files (.so or .dylib). 

I found a way to tell MAMP to listen MariaDB (brew install mariadb) with a more flexible and extendable MySQL. The folder of the plugins is not empty and contains a few ones already, mysql_jwt.so is added into it by following your 2015 instructions and it's 100% working.

Thanks for all, and sorry for the inconvenience

**Comment by yfuruyama** [comment]
Thank you for sharing the detailed diagnoses. Good to know that it's resolved on your side!
